/**
 * IndexedDB data layer. Implementation lives in ./db/*; this module re-exports
 * the public API so callers import from 'lib/db' as before.
 */
export {
  setAutoSync,
  initDB,
  openDB,
} from './db/core';
export {
  getAllJobs,
  getAllJobsByGroupId,
  getAllJobsForSync,
  getJobsByIds,
  getJob,
  addJob,
  updateJob,
  deleteJob,
} from './db/jobs';
export {
  getAllSystems,
  getAllSystemsForSync,
  addSystem,
  getAllPricingVariables,
  getAllPricingVariablesForSync,
  addPricingVariable,
  updateSystem,
  deleteSystem,
  updatePricingVariable,
  deletePricingVariable,
  getAllChipBlends,
  getAllChipBlendsForSync,
  getChipBlend,
  addChipBlend,
  updateChipBlend,
  deleteChipBlend,
  getAllBaseCoatColors,
  getAllBaseCoatColorsForSync,
  getBaseCoatColor,
  addBaseCoatColor,
  updateBaseCoatColor,
  deleteBaseCoatColor,
  getAllProducts,
  getAllProductsForSync,
  getProduct,
  addProduct,
  updateProduct,
  deleteProduct,
} from './db/catalog';
export {
  getCosts,
  saveCosts,
  updateCosts,
  getDefaultCosts,
  getPricing,
  savePricing,
  updatePricing,
  getDefaultPricing,
  getAllCommTemplatesForSync,
  getAllCommTemplates,
  addCommTemplate,
  updateCommTemplate,
  deleteCommTemplate,
} from './db/settings';
export {
  getAllLaborers,
  getAllLaborersForSync,
  getActiveLaborers,
  addLaborer,
  updateLaborer,
  deleteLaborer,
} from './db/laborers';
export {
  getAllChipInventory,
  getAllChipInventoryForSync,
  saveChipInventory,
  deleteChipInventory,
  getAllTintInventory,
  getAllTintInventoryForSync,
  saveTintInventory,
  deleteTintInventory,
  getAllCoatingInventory,
  getAllCoatingInventoryForSync,
  saveCoatingInventory,
  deleteCoatingInventory,
  ensureCoatingInventorySeeded,
  applyLegacyCoatingToSkus,
  getTopCoatInventory,
  saveTopCoatInventory,
  getBaseCoatInventory,
  saveBaseCoatInventory,
  getMiscInventory,
  saveMiscInventory,
  getAllShoppingItemsForSync,
  getAllShoppingItems,
  addShoppingItem,
  updateShoppingItem,
  deleteShoppingItem,
} from './db/inventory';
export {
  getAllCustomers,
  getAllCustomersForSync,
  addCustomer,
  updateCustomer,
  deleteCustomer,
} from './db/customers';
export {
  getAllLeads,
  getAllLeadsForSync,
  getLead,
  updateLead,
  deleteLead,
  getAllLeadAppointments,
  getAllLeadAppointmentsForSync,
  updateLeadAppointment,
  deleteLeadAppointment,
  getAllAdSpend,
  getAllAdSpendForSync,
  updateAdSpend,
  setAdSpendForMonth,
  deleteAdSpend,
} from './db/leads';
export {
  getAllReferralServicesForSync,
  getAllReferralServices,
  addReferralService,
  updateReferralService,
  deleteReferralService,
  getAllReferralAssociatesForSync,
  getAllReferralAssociates,
  addReferralAssociate,
  updateReferralAssociate,
  deleteReferralAssociate,
} from './db/referrals';
export type { ChipBlend } from './db/catalog';
