-- drop_backups_table: applied to production before the baseline was taken.
--
-- Its changes are already part of 20260928235900_baseline.sql, so this file is
-- intentionally empty. It exists because production's migration history lists
-- this version, and the Supabase CLI requires every recorded version to have a
-- matching local file.
--
-- Original SQL: no file in the repo (it was run from the Supabase dashboard)
