-- sync_lww_guard_all_tables: applied to production before the baseline was taken.
--
-- Its changes are already part of 20260928235900_baseline.sql, so this file is
-- intentionally empty. It exists because production's migration history lists
-- this version, and the Supabase CLI requires every recorded version to have a
-- matching local file.
--
-- Original SQL: supabase/legacy_migrations/migration_fix_updated_at_lww.sql
